// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDER1uQca0ko-GTvtgWfsjHto86QkrmPjU',
    appId: '1:852562619966:web:32261a2c1794cd7545ab6f',
    messagingSenderId: '852562619966',
    projectId: 'dhyaan-67e31',
    authDomain: 'dhyaan-67e31.firebaseapp.com',
    storageBucket: 'dhyaan-67e31.firebasestorage.app',
    measurementId: 'G-QMMX019ET0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0ZrpbOXHJY36xpIYqMpg0HoO8s0-r1U',
    appId: '1:852562619966:android:c4257e48dc533eed45ab6f',
    messagingSenderId: '852562619966',
    projectId: 'dhyaan-67e31',
    storageBucket: 'dhyaan-67e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2TdfC8Nfy7yF8tE-d0fmYdNlNeR9mbrQ',
    appId: '1:852562619966:ios:f070ae6e10f2445545ab6f',
    messagingSenderId: '852562619966',
    projectId: 'dhyaan-67e31',
    storageBucket: 'dhyaan-67e31.firebasestorage.app',
    iosBundleId: 'com.priyanshu.dhyan.dhyan',
  );
}
